/*
 * COPYRIGHT:         See COPYING in the top level directory
 * PROJECT:           Odyssey system libraries
 * PURPOSE:           Implementation of log
 * FILE:              lib/sdk/crt/math/amd64/log.S
 * PROGRAMMER:        Timo Kreuzer (timo.kreuzer@odyssey.org)
 */

/* INCLUDES ******************************************************************/

#include <asm.inc>

/* CODE **********************************************************************/
.code64

PUBLIC log
log:
    UNIMPLEMENTED log
    ret

END
